export const products = [
  {
    id: '1',
    name: 'Northern Lights (Indica)',
    category: 'Flower',
    price: 150,
    image: 'https://picsum.photos/seed/cannabis1/800/800?blur=2',
    thc: '18%',
    cbd: '1%',
    effects: ['Relaxed', 'Sleepy', 'Happy'],
    flavors: ['Pine', 'Earthy', 'Sweet'],
    description: 'A legendary indica strain known for its fast-acting, full-body relaxation. Perfect for evening use and unwinding after a long day.',
    tiers: [
      { weight: '1g', price: 150 },
      { weight: '3.5g', price: 450 },
      { weight: '7g', price: 800 },
    ],
    stock: 12,
    popular: true,
  },
  {
    id: '2',
    name: 'Sour Diesel (Sativa)',
    category: 'Flower',
    price: 160,
    image: 'https://picsum.photos/seed/cannabis2/800/800?blur=2',
    thc: '22%',
    cbd: '<1%',
    effects: ['Energetic', 'Creative', 'Uplifted'],
    flavors: ['Diesel', 'Citrus', 'Pungent'],
    description: 'An invigorating sativa named after its pungent, diesel-like aroma. Delivers fast-acting, energizing, and dreamy cerebral effects.',
    tiers: [
      { weight: '1g', price: 160 },
      { weight: '3.5g', price: 480 },
      { weight: '7g', price: 850 },
    ],
    stock: 5,
    popular: false,
  },
  {
    id: '3',
    name: 'Wellness Starter Kit',
    category: 'Bundle',
    price: 950,
    image: 'https://picsum.photos/seed/cannabis3/800/800?blur=2',
    thc: 'Varies',
    cbd: 'Varies',
    effects: ['Balanced', 'Exploratory'],
    flavors: ['Mixed'],
    description: 'The perfect introduction to our premium selection. Includes 1g of Indica, 1g of Sativa, a premium grinder, and rolling papers.',
    tiers: [
      { weight: '1 Kit', price: 950 },
    ],
    stock: 20,
    popular: true,
  },
  {
    id: '4',
    name: 'CBD Sleep Tincture',
    category: 'Wellness',
    price: 600,
    image: 'https://picsum.photos/seed/cannabis4/800/800?blur=2',
    thc: '0%',
    cbd: '1000mg',
    effects: ['Sleepy', 'Calm', 'Relaxed'],
    flavors: ['Peppermint'],
    description: 'A broad-spectrum CBD tincture formulated with chamomile and melatonin to promote deep, restorative sleep.',
    tiers: [
      { weight: '30ml', price: 600 },
    ],
    stock: 50,
    popular: false,
  }
];
